name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login autobrowser.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

      # Build and tag each image with the commit SHA as a tag (or use "latest")
      - name: Build xcrawler-chrome image
        run: |
          docker build \
            -t autobrowser.azurecr.io/autobrowser-chrome:${{ github.sha }} \
            -f docker/chrome/prod/Dockerfile .
      
      - name: Build xcrawler-proxy image
        run: |
          docker build \
            -t autobrowser.azurecr.io/autobrowser-proxy:${{ github.sha }} \
            -f docker/proxy/Dockerfile .

      - name: Build xcrawler-multiplex image
        run: |
          docker build \
            -t autobrowser.azurecr.io/autobrowser-multiplex:${{ github.sha }} \
            -f docker/multiplex_proxy/Dockerfile .

      - name: Build xcrawler-captcha_solver image
        run: |
          docker build \
            -t autobrowser.azurecr.io/autobrowser-captcha_solver:${{ github.sha }} \
            -f docker/captcha_solver/Dockerfile .

      - name: Build xcrawler-nginx image
        run: |
          docker build \
            -t autobrowser.azurecr.io/autobrowser-nginx:${{ github.sha }} \
            -f docker/nginx/Dockerfile .

      # Push all the images to ACR
      - name: Push images to ACR
        run: |
          docker push autobrowser.azurecr.io/autobrowser-chrome:${{ github.sha }}
          docker push autobrowser.azurecr.io/autobrowser-proxy:${{ github.sha }}
          docker push autobrowser.azurecr.io/autobrowser-multiplex:${{ github.sha }}
          docker push autobrowser.azurecr.io/autobrowser-captcha_solver:${{ github.sha }}
          docker push autobrowser.azurecr.io/autobrowser-nginx:${{ github.sha }}
